## Numpy

In [1]:
import numpy as np

### Basic exercises

####  Ceate a 1D array of numbers from 0 to 9

In [ ]:
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


#### Create a 3×3 numpy array of all True’s 

In [ ]:
arr_true = np.ones((3, 3), dtype=bool)
print(arr_true)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


#### Replace all odd numbers in arr with -1

In [ ]:
# Input
arr = np.arange(10)

arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### Convert a 1D array to a 2D array with 2 rows

In [ ]:
# Input
arr = np.arange(10)
print(arr)

arr_2d = arr.reshape(2, 5)
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Stack arrays a and b vertically and then horizontally

In [ ]:
# Input
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

vertically_stacked = np.vstack((a, b))
horizontally_stacked = np.hstack((a, b))
print("Vertically Stacked:\n", vertically_stacked)
print("Horizontally Stacked:\n", horizontally_stacked)

Vertically Stacked:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Horizontally Stacked:
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### Find positions where elements of a and b match

In [ ]:
# Input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

matches = np.where(a == b)
print("Matching positions:", matches)

Matching positions: (array([1, 3, 5, 7]),)


####  Get all items between 5 and 10 from a

In [ ]:
# Input
a = np.arange(15)

filtered_items = a[(a > 5) & (a < 10)]
print("Filtered items:", filtered_items)

Filtered items: [6 7 8 9]


#### Get the positions of top 5 maximum values in a given array a

In [ ]:
# Input
from array import array


np.random.seed(100)
a = np.random.uniform(1, 50, 20)
print(a)

top_5_positions = np.argpartition(a, -5)[-5:]
print("Positions of top 5 maximum values:", top_5_positions)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
Positions of top 5 maximum values: [18  7  3 10 15]


#### Compute the min-by-max (i.e. min/max) for each row for given 2d numpy array (see [apply_along_axis](https://numpy.org/doc/stable/reference/generated/numpy.apply_along_axis.html#numpy-apply-along-axis))

In [ ]:
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

min_by_max = np.min(a, axis=1) / np.max(a, axis=1)
print("Min-by-Max for each row:", min_by_max)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
Min-by-Max for each row: [0.44444444 0.125      0.5        1.         0.11111111]


####  Find the duplicate entries in the given numpy array and mark them as True. First time occurrences should be False.

In [ ]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

duplicates = np.zeros_like(a, dtype=bool)
for i in range(len(a)):
    if a[i] in a[:i]:
        duplicates[i] = True
print('Duplicate entries marked as True:', duplicates)

Array:  [0 0 3 0 2 4 2 2 2 2]
Duplicate entries marked as True: [False  True False  True False False  True  True  True  True]


#### Find the index of 5th repetition of number 1 in x
Make use of numpy.where

In [ ]:
# Input
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
repetition_indices = np.where(x == 1)[0]
if len(repetition_indices) >= n:
    index_of_nth_repetition = repetition_indices[n - 1]
    print(f"Index of {n}th repetition of number 1:", index_of_nth_repetition)
else:
    print(f"Number 1 does not repeat {n} times in the array.")

Index of 5th repetition of number 1: 8


#### Compute the moving average of window size 3, for the given 1D array
Make use of numpy.convolve

In [ ]:
# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

window_size = 3
moving_average = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')
print("Moving average with window size 3:", moving_average)

Moving average with window size 3: [6.33333333 6.         5.66666667 4.66666667 3.66666667 2.
 3.66666667 3.        ]


### Iris dataset

#### Import the iris dataset from iris.txt
See np.genfromtxt, load the dataset with dtype=np.str

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Input filepath
FILEPATH = '../data/iris.txt'
iris_data = np.genfromtxt(FILEPATH, delimiter=',', dtype=str)
print("Iris dataset imported from iris.txt:\n", iris_data)

Iris dataset imported from iris.txt:
 [['5.1' '3.5' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa']
 ['5.4' '3.9' '1.3' '0.4' 'Iris-setosa']
 ['5.1' '3.5' '1.4' '0.3' 'Iris-setosa']
 ['5.7' '3.8' '1.7' '0.3' 'Iris-setosa']
 ['5.1' '3.8' '1.5' '0.3' 'Iris-setosa']
 ['5.4' '3.4' '1.7' '0.2' 'Iris-setosa']
 ['5.1' '3.7' '1.5' '0.4' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['5.1' '3.3' '1.7'

#### Print the unique labels of the dataset

In [ ]:
unique_labels = np.unique(iris_data[:, -1])
print("Unique labels in the dataset:", unique_labels)

Unique labels in the dataset: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


#### Find how many samples (i.e. rows) we have for each unique label

In [ ]:
for label in unique_labels:
    count = np.sum(iris_data[:, -1] == label)
    print(f"Number of samples for label '{label}': {count}")

Number of samples for label 'Iris-setosa': 50
Number of samples for label 'Iris-versicolor': 50
Number of samples for label 'Iris-virginica': 50


#### Find the mean, median, standard deviation of iris's sepallength (1st column)
See np.genfromtxt, load only the 1st column with the appropiate data type

In [ ]:
sepallength = iris_data[:, 0].astype(float)
mean_sepallength = np.mean(sepallength)
median_sepallength = np.median(sepallength)
std_sepallength = np.std(sepallength)
print(f"Mean of sepallength: {mean_sepallength}")
print(f"Median of sepallength: {median_sepallength}")
print(f"Standard deviation of sepallength: {std_sepallength}")

Mean of sepallength: 5.843333333333334
Median of sepallength: 5.8
Standard deviation of sepallength: 0.8253012917851409


####  Find the mean, median, standard deviation of iris's sepallength (1st column) for each unique labels

In [ ]:
for label in unique_labels:
    sepallength_label = iris_data[iris_data[:, -1] == label, 0].astype(float)
    mean_label = np.mean(sepallength_label)
    median_label = np.median(sepallength_label)
    std_label = np.std(sepallength_label)
    print(f"Label: {label}")
    print(f"  Mean of sepallength: {mean_label}")
    print(f"  Median of sepallength: {median_label}")
    print(f"  Standard deviation of sepallength: {std_label}")

Label: Iris-setosa
  Mean of sepallength: 5.006
  Median of sepallength: 5.0
  Standard deviation of sepallength: 0.3489469873777391
Label: Iris-versicolor
  Mean of sepallength: 5.936
  Median of sepallength: 5.9
  Standard deviation of sepallength: 0.5109833656783751
Label: Iris-virginica
  Mean of sepallength: 6.587999999999998
  Median of sepallength: 6.5
  Standard deviation of sepallength: 0.6294886813914926


####  Create a new column for volume in iris, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
petallength = iris_data[:, 2].astype(float)
sepal_length = iris_data[:, 0].astype(float)
volume = (np.pi * petallength * sepal_length**2) / 3
iris_data_with_volume = np.hstack((iris_data, volume.reshape(-1, 1)))
print("Iris dataset with new volume column:\n", iris_data_with_volume)

Iris dataset with new volume column:
 [['5.1' '3.5' '1.4' '0.2' 'Iris-setosa' '38.13265162927291']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa' '35.200498485922445']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa' '30.0723720777127']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa' '33.238050274980004']
 ['5.0' '3.6' '1.4' '0.2' 'Iris-setosa' '36.65191429188092']
 ['5.4' '3.9' '1.7' '0.4' 'Iris-setosa' '51.911677007917746']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa' '31.022180256648003']
 ['5.0' '3.4' '1.5' '0.2' 'Iris-setosa' '39.269908169872416']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa' '28.38324242763259']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa' '37.714819806345474']
 ['5.4' '3.7' '1.5' '0.2' 'Iris-setosa' '45.80442088933919']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa' '38.60389052731138']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa' '33.77840421139745']
 ['4.3' '3.0' '1.1' '0.1' 'Iris-setosa' '21.298950993787603']
 ['5.8' '4.0' '1.2' '0.2' 'Iris-setosa' '42.273270746704256']
 ['5.7' '4.4' '1.5' '0.4' 'Iris-setosa' 

#### Randomly sample iris's species such that setosa is twice the number of versicolor and virginica
See [numpy.random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html#numpy-random-choice)

In [28]:
sampled_species = np.random.choice(unique_labels, size=60, p=[0.5, 0.25, 0.25])
print("Sampled species:", sampled_species)
print("\nValue counts:")
unique_sampled, counts = np.unique(sampled_species, return_counts=True)
for label, count in zip(unique_sampled, counts):
    print(f"{label}: {count}")

Sampled species: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa']

Value counts:
Iris-setosa:

#### Sort the iris dataset based on sepallength column

In [ ]:
sorted_indices = np.argsort(iris_data[:, 0].astype(float))
sorted_iris_data = iris_data[sorted_indices]
print("Iris dataset sorted by sepallength:\n", sorted_iris_data)

Iris dataset sorted by sepallength:
 [['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.4' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.4' '3.0' '1.3' '0.2' 'Iris-setosa']
 ['4.5' '2.3' '1.3' '0.3' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['4.6' '3.2' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.3' 'Iris-setosa']
 ['4.8' '3.1' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.9' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.9' '2.4' '3.3' '1.0' 'Iris-versicolor']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['4.9' '2.5' '4.5' '1.7' 'Iris-virginica']
 ['5.0' '3.5' '1.3' '0.3' 'Iris-setosa']
 ['5.0' '3.3'

#### Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
from numpy import astype


petal_length = iris_data[:, 2].astype(float)
values, counts = np.unique(petal_length, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
print(f"The most frequent value of petal length is: {most_frequent_value}")

The most frequent value of petal length is: 1.5


#### Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset

see [np.argwhere](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html#numpy-argwhere)

In [ ]:
first_occurrence = np.argwhere(iris_data[:, 3].astype(float) > 1.0)[0][0]
print(f"The position of the first occurrence of a value greater than 1.0 in petalwidth is: {first_occurrence}")

The position of the first occurrence of a value greater than 1.0 in petalwidth is: 50


#### Get the rows having petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [ ]:
filtered_rows = iris_data[(iris_data[:, 2].astype(float) > 1.5) & (iris_data[:, 0].astype(float) < 5.0)]
print("Rows with petallength > 1.5 and sepallength < 5.0:\n", filtered_rows)

Rows with petallength > 1.5 and sepallength < 5.0:
 [['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.9' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.1' '1.6' '0.2' 'Iris-setosa']
 ['4.9' '2.4' '3.3' '1.0' 'Iris-versicolor']
 ['4.9' '2.5' '4.5' '1.7' 'Iris-virginica']]
